### PR TITLE
README changes, botplay adjustment

### PR DESCRIPTION
**Pull request by crowplexus**
just stuff that hasn't been made on the original repo and I was too dumb to fix it back then

### CODE REVIEW

**Review by MemeHoovy — COMMENTED** [review]
my friend @LEVIXDDLMAO made that botplay change for a reason though, see https://github.com/Z11Coding/Beat-Engine-Revived/pull/1

**Comment by crowplexus** [comment]
the previous botplay change wasn't as neutral as "user" and still might piss someone off

**Review by MemeHoovy — APPROVED** [review]
well okay then 🤷🏻‍♂️

**Comment by LEVIXDDLMAO** [comment]
xd

**Review by LEVIXDDLMAO — APPROVED** [review]

**Pull request merged**
